# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MobxDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobxDemo

     rn_path = '../node_modules/react-native'

     pod 'React', :path => rn_path, :subspecs => [
        'ART',
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'RCTCameraRoll'
      ]
      pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
      # React Native third party dependencies podspecs
      # pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
      pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
      # If you are using React Native <0.54, you will get the following error:
      # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
      # Use the following line instead:
      # pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
      pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

      pod 'RNSVG', :path => '../node_modules/react-native-svg'
      pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
      pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
      pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


end
